# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: vanshikanpandey@gmail.com
author_name: Vanshika Pandey
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: Algorand_Assignment_1

